spring:
  application:
    name: pdf2swf-service

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

info:
  name: test
